name: tldart
description: Fast tldr client written in dart 
version: 1.0.0
repository: https://github.com/Yakiyo/tldart

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ansi: ^0.2.2
  archive: ^3.3.6
  args: ^2.4.0
  http: ^0.13.5
  path: ^1.8.3
  # toml: ^0.14.0
  
executables:
  tldr:
