name: Build and Release
on:
  release:
    types: [created]

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    permissions: read-all
    
    strategy:
      matrix:
        extension: ['linux', 'macos', 'windows']
        include:
          - extension: linux
            os: ubuntu-latest
            file: tldr
          - extension: macos
            os: macos-latest
            file: tldr
          - extension: windows
            os: windows-latest
            file: tldr.exe

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Install deps
        run: dart pub get

      - name: Build Executable for ${{ matrix.os }}
        run: dart compile exe bin/tldr.dart -o ${{ matrix.file }}

      - name: Zip Binaries
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a tldr-${{ matrix.extension }}-${{ env.RELEASE_VERSION }}.zip ${{ matrix.file }}
          else
            zip  tldr-${{ matrix.extension }}-${{ env.RELEASE_VERSION }}.zip ${{ matrix.file }}
          fi

      - name: Get latest release
        id: latest_release_info
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          latest: true

      - name: Upload Files
        run: gh release upload ${{ env.RELEASE_VERSION }} tldr-${{ matrix.extension }}-${{ env.RELEASE_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CUSTOM }}
